


export const FETCH_DATA = "FETCH_DATA";
export const FETCHED_SUCCESSFULLY = "FETCHED_SUCCESSFULLY";
export const FETCH_FAILED = "FETCH_FAILED";
export const WAS_BUTTON_TOUCHED = "WAS_BUTTON_TOUCHED";
